apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: RELEASE
  name: RELEASE-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: SIZE
  storageClassName: do-block-storage
